version: '3'

services:

  map_service:
    build:
      context: map_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my_network

  auth_service:
    build:
      context: auth_app
      dockerfile: Dockerfile.auth
    ports:
      - "8001:8001"
    networks:
      - my_network

networks:
  my_network:
